### ISSUE TITLE
Version v0.1.1 does not point to a commit

### ISSUE THREAD

**Issue by teleivo** [phinze/puppet-sudoers#10]
Hello!

I ran into troubles when setting my .fixtures.yml to your latest version tag https://github.com/phinze/puppet-sudoers/releases/tag/v0.1.1

I then cloned the repo and saw that the latest tag in the repo is actually https://github.com/phinze/puppet-sudoers/releases/tag/v0.1.0 which points to the latest commit  5708f80d3ce8dc817e1fc28a296cb0a88d87f403

v0.1.1 doesnt seem to point to a commit in the repo.

I then downloaded the zips of the source code from both versions and found that there is at least no difference in allowed_command.pp

Could you please rectify this. Not sure how the version tags in github then relate to the forge.

Thanks a lot!

**Comment by teleivo** [comment]
@phinze were you able to confirm my issue? thanks!

**Comment by phinze** [comment]
Hi @teleivo - not quite sure what you mean. I see two tags here.

![zsh](https://cloud.githubusercontent.com/assets/37534/13402933/39ce9bf4-ded8-11e5-9ae1-ea801cfd364b.png)

Going to cut v0.1.2 now and push a tag - hopefully that will sort things out for you?

**Comment by phinze** [comment]
Ah I see what you mean now - v0.1.1 was accidentally cut from a floating commit that didn't make it to master. Fixed that up with v0.1.2 which I just pushed to the forge!

Let me know if you are still having issues w/ the latest release. :+1:

**Comment by teleivo** [comment]
@phinze works fine now, thank you :+1:
